#!/usr/bin/env bash

oscheck=$(grep -Po "(?<=^ID=).+" /etc/os-release | sed 's/"//g')
builddir=/home/$username/.dwm
username=$(id -u -n 1000)

echo "Do you want to install the $(gum style --bold "alacritty") terminal emulator with a custom $(gum style --bold --foreground "#81A1C1" "nord theme")?" 
echo "This will $(gum style --bold "remove existing alacritty configuration")." # add a way to back up configs.

if [[ $oscheck == "arch" ]]
then
    export GUM_CHOOSE_CURSOR_FOREGROUND="#0f94d2"

    CHOICE=$(gum choose "Yes" "No")

    if [[ "$CHOICE" == "Yes" ]]
    then
        gum spin --spinner dot --title "Installing $(gum style --bold --foreground "#0f94d2" "alacritty") terminal emulator with the $(gum style --bold --foreground "#81A1C1" "nord theme")." -- sleep 5
        pacman -S alacritty
        mkdir /home/$username/.config
        cp -r $builddir/configs/alacritty /home/$username/.config/alacritty
        chown $username:$username /home/$username/.config
        chown $username:$username /home/$username/.config/alacritty
    elif [[ "$CHOICE" == "No" ]]
    then
        echo "Okay, I will not install the $(gum style --bold --foreground "#0f94d2" "alacritty") terminal emulator."
    fi

elif [[ $oscheck == "debian" ]]
then
    export GUM_CHOOSE_CURSOR_FOREGROUND="#a80030"

    CHOICE=$(gum choose "Yes" "No")

    if [[ "$CHOICE" == "Yes" ]]
    then
        gum spin --spinner dot --title "Installing $(gum style --bold --foreground "#a80030" "alacritty") terminal emulator with the $(gum style --bold --foreground "#81A1C1" "nord theme")." -- sleep 5
        nala install alacritty -y
        mkdir /home/$username/.config
        cp -r $builddir/configs/alacritty /home/$username/.config/alacritty
        chown $username:$username /home/$username/.config
        chown $username:$username /home/$username/.config/alacritty
    elif [[ "$CHOICE" == "No" ]]
    then
        echo "Okay, I will not install the $(gum style --bold --foreground "#a80030" "alacritty") terminal emulator."
    fi

elif [[ $oscheck == "fedora" ]]
then
    export GUM_CHOOSE_CURSOR_FOREGROUND="#60a5fa"

    CHOICE=$(gum choose "Yes" "No")

    if [[ "$CHOICE" == "Yes" ]]
    then
        gum spin --spinner dot --title "Installing $(gum style --bold --foreground "#60a5fa" "alacritty") terminal emulator with the $(gum style --bold --foreground "#81A1C1" "nord theme")." -- sleep 5
        dnf install alacritty -y
        mkdir /home/$username/.config
        cp -r $builddir/configs/alacritty /home/$username/.config/alacritty
        chown $username:$username /home/$username/.config
        chown $username:$username /home/$username/.config/alacritty
    elif [[ "$CHOICE" == "No" ]]
    then
        echo "Okay, I will not install the $(gum style --bold --foreground "#60a5fa" "alacritty") terminal emulator."
    fi
fi