#!/usr/bin/env bash

username=$(id -u -n 1000)

echo "Do you want to install the $(gum style --bold "yay") $(gum style --bold --foreground "#0f94d2" "AUR") helper?"

CHOICE=$(gum choose "Yes" "No")

if [[ "$CHOICE" == "Yes" ]]
then
    echo "Installing the $(gum style --bold yay) $(gum style --bold --foreground "#0f94d2" "AUR") helper."
    gum spin --spinner dot --title "Installing $(gum style --bold yay) $(gum style --bold --foreground "#0f94d2" "AUR") helper." -- sleep 5
    cd /home/$username
    git clone https://aur.archlinux.org/yay-bin.git ./yay
    cd yay
    makepkg -si
    cd /home/$username
    rm -rf ./yay
    echo "Installed the $(gum style --bold yay) $(gum style --bold --foreground "#0f94d2" "AUR") helper."
elif [[ "$CHOICE" == "No" ]]
then
    echo "Okay, I will not install $(gum style --bold "yay")."
fi


