#!/usr/bin/env bash

oscheck=$(grep -Po "(?<=^ID=).+" /etc/os-release | sed 's/"//g')
username=$(id -u -n 1000)

echo "Do you want to install the custom dwm-mko $(gum style --bold --foreground "#81A1C1" "conky")?"
echo "This will $(gum style --bold "remove the existing") $(gum style --bold --foreground "#81A1C1" "conky") $(gum style --bold "configuration")."

CHOICE=$(gum choose "Yes" "No")

if [[ $oscheck == "arch"]]
then
    export GUM_CHOOSE_CURSOR_FOREGROUND="#0f94d2"

    if [[ "$CHOICE" == "Yes" ]]
    then
        gum spin --spinner dot --title "Installing the dwm $(gum style --bold "conky") with the $(gum style --bold --foreground "#81A1C1" "nord theme")." -- sleep 5
        pacman -S conky --noconfirm
        mkdir -p /home/$username/.config/
        cp -r $builddir/configs/conky /home/$username/.config/conky
        chown $username:$username /home/$username/.config
        chown $username:$username /home/$username/.config/conky
        echo "$(gum style --bold "Conky") has been installed!"
    elif [[ "$CHOICE" == "No" ]]
    then
        echo "Okay, I will not install $(gum style --bold "conky")."
    fi
    
elif [[ $oscheck == "debian" ]]
then
    export GUM_CHOOSE_CURSOR_FOREGROUND="#a80030"

    if [[ "$CHOICE" == "Yes" ]]
    then
        gum spin --spinner dot --title "Installing the dwm $(gum style --bold "conky") with the $(gum style --bold --foreground "#81A1C1" "nord theme")." -- sleep 5
        nala install conky -y
        mkdir -p /home/$username/.config/
        cp -r $builddir/configs/conky /home/$username/.config/conky
        chown $username:$username /home/$username/.config
        chown $username:$username /home/$username/.config/conky
        echo "$(gum style --bold "Conky") has been installed!"
    elif [[ "$CHOICE" == "No" ]]
    then
        echo "Okay, I will not install $(gum style --bold "conky")."
    fi

elif [[ $oscheck == "fedora" ]]
then
    export GUM_CHOOSE_CURSOR_FOREGROUND="#60a5fa"

    if [[ "$CHOICE" == "Yes" ]]
    then
        gum spin --spinner dot --title "Installing the dwm $(gum style --bold "conky") with the $(gum style --bold --foreground "#81A1C1" "nord theme")." -- sleep 5
        dnf install conky -y
        mkdir -p /home/$username/.config/
        cp -r $builddir/configs/conky /home/$username/.config/conky
        chown $username:$username /home/$username/.config
        chown $username:$username /home/$username/.config/conky
        echo "$(gum style --bold "Conky") has been installed!"
    elif [[ "$CHOICE" == "No" ]]
    then
        echo "Okay, I will not install $(gum style --bold "conky")."
    fi
fi