#!/usr/bin/env bash

username=$(id -u -n 1000)
builddir=/home/$username/.dwm

echo "Do you want to install the $(gum style --bold --foreground "#5277c3" "nix") package manager?"
CHOICE=$(gum choose "Yes" "No")

if [[ "$CHOICE" == "Yes" ]]
then
    echo "$(gum style --bold "Single-User") or $(gum style --bold "Multi-User") installation?"
    SING_MULTI=$(gum choose "Single-User Installation" "Multi-User Installation")
        if [[ "$SING_MULTI" == "Multi-User Installation" ]]
        then
            gum spin --spinner dot --title "Installing the (Multi-User) $(gum style --bold --foreground "#5277c3" "nix") package manager." -- sleep 10
            sh <(curl -L https://nixos.org/nix/install) --daemon
            echo "Installed the (Multi-User) $(gum style --bold --foreground "#5277c3" "nix") package manager."
        elif [[ "$SING_MULTI" == "Multi-User Installation" ]]
        then
            gum spin --spinner dot --title "Installing the (Single-User) $(gum style --bold --foreground "#5277c3" "nix") package manager." -- sleep 10
            runuser -u mko "bash" "$builddir/scripts/nix/nix-single-install"
            echo "Installed the (Single-User) $(gum style --bold --foreground "#5277c3" "nix") package manager."
        fi
fi