#!/usr/bin/env bash

username=$(id -u -n 1000)

# Make the directory where the fonts are gonna be installed
mkdir -p /usr/share/fonts/OTF
cd /usr/share/fonts/OTF

# Grabbing Fira Mono Nerd Font
wget -O FiraMono.zip https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.0/FiraMono.zip

# Setting Fira Mono Nerd Font up
unzip -qq FiraMono.zip
rm -f readme.md
rm -f LICENSE
rm -f FiraMono.zip

# Grabbing Raleway
wget -O raleway.zip https://github.com/theleagueof/raleway/releases/download/4.101/Raleway-4.101.zip

# Setting Raleway up
mv ./Raleway-4.101/static/OTF/* /usr/share/fonts/OTF/
rm -rf Raleway-4.101
rm -f raleway.zip

# Reload cache
fc-cache -vf

echo "################ Fonts installed! ################"
